### PR TITLE
make search query strict cql

### PR DESCRIPTION
**Pull request by pjohans**
as far as i could see all searches went throug the ting_search.module::_ting_search_quote method. svi wrote a small cql parser for bibliotek.dk, and basically i copy/pasted the code to the ting_search.module.

### CODE REVIEW

**Comment by pjohans** [comment]
as i understand the change to opensearch 3.2 is postponed, and this change is meant for that. I suggest that we wait a while ..

**Comment by cableman** [comment]
The current information is that the current data-well (3.0) will be closed at 01/02/15, so this is highly important and how do it relate to https://github.com/ding2/ting_search/pull/9. These things are planed to be part of release 1.1

**Comment by pjohans** [comment]
okay i will finish the pull request right now

**Comment by guddo** [comment]
@cableman When is 7.x-1.1 planned to be released?

**Comment by cableman** [comment]
I don't have a date, but it has to be before 01/02/15 as the current supported data-well (3.0) is begin closed at that point.

**Comment by guddo** [comment]
Do you expect this to be solved, tested and deployed to all websites within the next 12 working days - being aware that this PR is not even merged yet? /cc @ding2tal/owners

**Comment by cableman** [comment]
It's the plan, DBC that have made the changes have tested them, so it should work. But please move this conversation over to http://platform.dandigbib.org/issues/467 so the project owners also see this and not only the developers :-D

**Comment by cableman** [comment]
This issue have been moved into: https://github.com/ding2/ting_search/pull/9/files

**Pull request closed without merging**
